### PR TITLE
generic: spi: Fix CS pin name collision in impl_spi!()

### LINKED ISSUE #109: macro impl_spi! creates name collision in atmega328pb
the macro `impl_spi!` creates a struct `ChipSelectPin`
https://github.com/Rahix/avr-hal/blob/3d255df0194ba2cdbbb086be61b9146a37df7963/avr-hal-generic/src/spi.rs#L89

this makes it impossible to declare two spi ports in the same module like `atmega328pb` does:
https://github.com/Rahix/avr-hal/blob/3d255df0194ba2cdbbb086be61b9146a37df7963/chips/atmega328p-hal/src/lib.rs#L162-L184

currently atmega328pb build is broken.

### PR DESCRIPTION
**Pull request by fneddy**
add a wrapper for the `impl_spi!` macro to allow setting a dedicated name for `pub struct ChipSelectPin`

### CODE REVIEW

File: avr-hal-generic/src/spi.rs [hunk 1]
```diff
@@ -132,7 +136,7 @@ macro_rules! impl_spi {
             ///
             /// The pins are not actually used directly, but they are moved into the struct in
             /// order to enforce that they are in the correct mode, and cannot be used by anyone
-            /// else while SPI is active.  CS is placed into a `ChipSelectPin` instance and given
+            /// else while SPI is active.  CS is placed into a `$ChipSelectPin` instance and given
```
Comment (Rahix) [inline avr-hal-generic/src/spi.rs:139]: I don't think macros will expand doc-comment content.

File: avr-hal-generic/src/spi.rs [hunk 2]
```diff
@@ -161,7 +165,7 @@ macro_rules! impl_spi {
...
```
Comment (Rahix) [inline avr-hal-generic/src/spi.rs:168]: Same here.

File: avr-hal-generic/src/spi.rs [hunk 3]
```diff
@@ -299,3 +303,63 @@ macro_rules! impl_spi {
         }
     };
 }
+
+
+/// Implement traits for a SPI interface
+#[macro_export]
+macro_rules! impl_spi {
```
Comment (Rahix) [inline avr-hal-generic/src/spi.rs:310]: I think it should be possible to do this without introducing a second macro if `impl_spi!` just invokes itself:

```rust
#[macro_export]
macro_rules! impl_spi {
    (
        $(#[$spi_attr:meta])*
        pub struct $Spi:ident {
            peripheral: $SPI:ty,
            pins: {
                sclk: $sclkmod:ident::$SCLK:ident,
                mosi: $mosimod:ident::$MOSI:ident,
                miso: $misomod:ident::$MISO:ident,
                cs: $csmod:ident::$CS:ident,
            }
        }
    ) => {
        $crate::impl_spi! {
            pub struct $Spi {
                peripheral: $SPI,
                pins: {
                    sclk: $sclkmod::$SCLK,
                    mosi: $mosimod::$MOSI,
                    miso: $misomod::$MISO,
                    cs: $csmod::$CS,
                }
            }
            pub struct ChipSelectPin;
        }
    };
    (
        $(#[$spi_attr:meta])*
        pub struct $Spi:ident {
            peripheral: $SPI:ty,
            pins: {
                sclk: $sclkmod:ident::$SCLK:ident,
                mosi: $mosimod:ident::$MOSI:ident,
                miso: $misomod:ident::$MISO:ident,
                cs: $csmod:ident::$CS:ident,
            }
        }
        pub struct $ChipSelectPin:ident;
    )
    => {
        // actual implementation ...
    };
}
```

File: chips/atmega328p-hal/src/lib.rs [hunk 4]
```diff
@@ -178,9 +179,10 @@ pub mod spi {
                 sclk: portc::PC1,
                 mosi: porte::PE3,
                 miso: portc::PC0,
-                cs: portc::PE2,
+                cs: porte::PE2,
```
Comment (Rahix) [inline chips/atmega328p-hal/src/lib.rs:182]: Nice catch, I wonder how this ever worked ...

**Review by Rahix — CHANGES_REQUESTED** [review]
Thanks a lot, this approach looks like the way to go!  I've left a few comments below.

File: chips/atmega328p-hal/src/lib.rs (hunk 4 above)
Comment (jkristell) [reply chips/atmega328p-hal/src/lib.rs:182]: I'm also surprised. Thanks for fixing this.

File: avr-hal-generic/src/spi.rs (hunk 3 above)
Comment (fneddy) [reply avr-hal-generic/src/spi.rs]: wow, this is clever. I'll try it.

**Review by Rahix — APPROVED** [review]
Looks good to me!  CI is passing so it seems to work fine.  I suppose you tested it for `ATmega328PB` as well?

**Comment by fneddy** [comment]
it compiles and a blinktest is working, but i currently have no SPI setup here. So you may declare it as "compiling-ok"

**Comment by Rahix** [comment]
Good enough for me, I don't see this change breaking anything runtime related ;)
