### PR TITLE
treewide: spi: Enforce proper CS pin usage

### LINKED ISSUE #27: SPI: CS must be configured before SPI peripheral
I'm trying to use the SPI library but it's not working as expected.  The `send` method works fine and returns without incident, but the `read` method blocks forever.

```
    let byte = block!(spi.send(5u8).and_then(|_| spi.read()));
    if let Ok(byte) = byte {
        ufmt::uwriteln!(&mut serial, "wrote read {}\r", byte).unwrap();
    } else {
        ufmt::uwriteln!(&mut serial, "not wrote read\r").unwrap();
    }
```
It never makes it past the `block` macro, it seems that it's returning WouldBlock forever.  All `read` does is try to flush, code here:

https://github.com/Rahix/avr-hal/blob/master/avr-hal-generic/src/spi.rs#L125

The is_write_in_progress is obviously true as expected, since a send was just executed.  But it seems that the write complete status register is not being set.

https://github.com/Rahix/avr-hal/blob/master/avr-hal-generic/src/spi.rs#L127

Documentation for the SPI interrupt flag is in section 18.5.2 of this document:

http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-7810-Automotive-Microcontrollers-ATmega328P_Datasheet.pdf

I'm trying to debug this but any suggestions are welcome.

### PR DESCRIPTION
**Pull request by jonahd-g**
/resolves #27 

Makes the proposed change to the SPI macro and the usage by ATmega328p.  Waiting for review and approval before making an attempt to update all other usages.

### CODE REVIEW

File: avr-hal-generic/src/spi.rs [hunk 1]
```diff
@@ -75,9 +75,29 @@ macro_rules! impl_spi {
...
+
+        /// Wrapper for the CS pin
+        ///
+        /// Used to contain the chip-select pin during operation to prevent its mode from being
+        /// changed from Output.  Implements
+        /// [`OutputPin`](https://docs.rs/embedded-hal/latest/embedded_hal/digital/v2/trait.OutputPin.html)
+        /// so that it can still be controlled.
+        pub struct ChipSelectPin($csmod::$CS<$crate::port::mode::Output>);
+
+        impl $crate::hal::digital::v2::OutputPin for ChipSelectPin {
```
Comment (Rahix) [inline avr-hal-generic/src/spi.rs:91]: Should also implement `StatefulOutputPin` and `ToggleableOutputPin` from _embedded-hal_ as well.

File: avr-hal-generic/src/spi.rs [hunk 2]
```diff
@@ -75,9 +75,29 @@ macro_rules! impl_spi {
...
+            type Error = <$csmod::$CS<$crate::port::mode::Output> as $crate::hal::digital::v2::OutputPin>::Error;
```
Comment (Rahix) [inline avr-hal-generic/src/spi.rs:92]: Rust syntax at its finest :D  I would just use the concrete type though, should be `$crate::void::Void` if I'm not mistaken.

File: avr-hal-generic/src/spi.rs [hunk 3]
```diff
@@ -94,19 +114,21 @@ macro_rules! impl_spi {
...
+            /// back so that its output state can be changed as needed.
             pub fn new(
                 peripheral: $SPI,
                 sclk: $sclkmod::$SCLK<$crate::port::mode::Output>,
                 mosi: $mosimod::$MOSI<$crate::port::mode::Output>,
                 miso: $misomod::$MISO<$crate::port::mode::Input<$crate::port::mode::PullUp>>,
+                cs: $csmod::$CS<$crate::port::mode::Output>,
                 settings: Settings
-            ) -> Self {
+            ) -> (Self, ChipSelectPin) {
```
Comment (Rahix) [inline avr-hal-generic/src/spi.rs:131]: This means we'll also need to update all SPI examples to look like

```rust
let (mut spi, _) = Spi::new();
```

and I'll have to document this change as a breakage for downstream users.

File: avr-hal-generic/src/spi.rs [hunk 4]
```diff
@@ -75,9 +75,29 @@ macro_rules! impl_spi {
...
             }
         }
     ) => {
+
+        /// Wrapper for the CS pin
+        ///
+        /// Used to contain the chip-select pin during operation to prevent its mode from being
+        /// changed from Output.  Implements
+        /// [`OutputPin`](https://docs.rs/embedded-hal/latest/embedded_hal/digital/v2/trait.OutputPin.html)
+        /// so that it can still be controlled.
```
Comment (Rahix) [inline avr-hal-generic/src/spi.rs:88]: I'd write something like:

_[...] prevent its mode from being changed from Output.  This is necessary because the SPI state machine would otherwise reset itself to SPI slave mode immediately._

_This wrapper can be used just like an output pin, because it implements all the same traits from embedded-hal._

**Review by Rahix — CHANGES_REQUESTED** [review]
Nice, thank you very much!  The design is solid, I've left a few comments but apart from that you can go ahead and update all the other HAL crates and examples :)

File: avr-hal-generic/src/spi.rs (hunk 1 above)
Comment (jonahd-g) [reply avr-hal-generic/src/spi.rs:91]: All right.  I wasn't sure if those were important, but I'll add it in.

File: avr-hal-generic/src/spi.rs (hunk 2 above)
Comment (jonahd-g) [reply avr-hal-generic/src/spi.rs:92]: Oh sweet, that makes it much easier.

File: avr-hal-generic/src/spi.rs (hunk 3 above)
Comment (jonahd-g) [reply avr-hal-generic/src/spi.rs:131]: Yeah, I'll make sure the examples get updated too.  I'll include a description of the breaking change in the changelog

**Comment by jonahd-g** [comment]
> The design is solid

Lol you don't get to say that when I mostly copied from your comment :wink:

**Comment by Rahix** [comment]
> Lol you don't get to say that when I mostly copied from your comment :wink:

Haha, I did not at all remember what I wrote back then, please forgive me :D

File: boards/arduino-leonardo/src/lib.rs [hunk 5]
```diff
@@ -93,14 +93,13 @@ pub fn delay_us(us: u16) {
 ///
 /// let mut pins = arduino_leonardo::Pins::new(dp.PORTB, dp.PORTC, dp.PORTD, dp.PORTE);
 ///
-/// pins.led_rx.into_output(&mut pins.ddr); // Chip Select must be set to output mode.
-///
 /// // Create SPI interface.
 /// let mut spi = arduino_leonardo::spi::Spi::new(
```
Comment (Rahix) [inline boards/arduino-leonardo/src/lib.rs:97]:
```suggestion
/// let (mut spi, mut cs) = arduino_leonardo::spi::Spi::new(
```

**Review by Rahix — APPROVED** [review]
LGTM!  Thanks a lot!
